## 1.2 Numpy Basic

In [3]:
import numpy as np

In [5]:
np.__version__

'1.26.4'

## Arreglos basicos

In [8]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [34]:
arr1 = np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [36]:
arr2 = np.array([1,2,3,4,5,6])
arr2

array([1, 2, 3, 4, 5, 6])

In [38]:
id(arr1)

2068402356112

In [40]:
id(arr2)

2068402355728

In [24]:
arr1 = arr2  # Esto no es recomendable
id(arr1)

2068117866224

In [42]:
arr1 = np.copy(arr2)
id(arr1)   # ya se asigna en otro espacio de memoria, pero con los mismos elementos

2068081057520

In [46]:
print(arr1)
print(arr2)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [48]:
type((1,2,3,4,5))

tuple

In [52]:
type(np.array([1,2,3,4,5]))

numpy.ndarray

In [56]:
type({'one': 1, 'two':2, 'three':3})

dict

In [58]:
np.array({'one': 1, 'two':2, 'three':3})

array({'one': 1, 'two': 2, 'three': 3}, dtype=object)

In [60]:
{1,2,2,2,2,2,2,3,4,5}

{1, 2, 3, 4, 5}

In [62]:
type({1,2,2,2,2,2,2,3,4,5})

set

In [64]:
np.array({1,2,2,2,2,2,2,3,4,5})

array({1, 2, 3, 4, 5}, dtype=object)

In [66]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
np.arange(3,10,5) # es como un for

array([3, 8])

In [80]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
len(a)

10

In [88]:
a.size

10

In [92]:
np.array([11,1.3, True])

array(['11', '1.3', 'hola'], dtype='<U32')

In [96]:
arr5 = np.array([11,1.3, True])  # lo transforma como en js XD
type(arr5[1])

numpy.float64

In [100]:
arr6 = np.array([11,1.3, 'XD']) 
type(arr6[2])

numpy.str_

In [109]:
np.array(["apple", "banana", "strawberryy"])

array(['apple', 'banana', 'strawberryy'], dtype='<U11')

In [127]:
print(np.arange(1,10,5))
print(np.linspace(1,10,10)) #Numero de datos que quiero. (Se utiliza mucho para graficar datos)

[1 6]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [129]:
np.linspace(-10,10,20)

array([-10.        ,  -8.94736842,  -7.89473684,  -6.84210526,
        -5.78947368,  -4.73684211,  -3.68421053,  -2.63157895,
        -1.57894737,  -0.52631579,   0.52631579,   1.57894737,
         2.63157895,   3.68421053,   4.73684211,   5.78947368,
         6.84210526,   7.89473684,   8.94736842,  10.        ])

In [131]:
np.array([[0,0,0], [0,0,0], [0,0,0]])

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [133]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [148]:
a = np.ones((3,3), dtype = "int") # se puede agregar como tercer argumento el tipo.
type(a[0,0])

numpy.int32

In [141]:
print(np.ones(3))
print(np.zeros(3))

[1. 1. 1.]
[0. 0. 0.]


# Arreglos multidimensionales

In [150]:
lis1 = [[1,2,3], [4,5,6],[7,8,9]]
lis1[0]

[1, 2, 3]

In [152]:
np.array(lis1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [156]:
arr2d = np.array(lis1)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Informacion valiosa de nuestros arreglos

In [159]:
print(arr2d.shape)
print(arr2.size)
print(arr2.ndim)

(3, 3)
6
1


In [167]:
arr3d = np.array([[[1,2,3],[4,5,6]], [[5,6,7],[8,9,10]]])
arr3d.ndim

3

In [171]:
print(arr3d[1,1,2]) # Metodologia Numpy
print(arr3d[0][1][2]) #Metodologia de listas

10
6


In [173]:
arrZeros = np.zeros((3,3), dtype = "int64")
arrZeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [175]:
arrZeros.astype("float32")

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

## Cambios de arreglo a matriz

In [178]:
a2 = np.arange(15)
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [186]:
a2.reshape(15,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

In [188]:
a3 = np.arange(15)
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [190]:
a3.shape = (15,1)
a3

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14]])

# Numeros aleatorios en Numpy

In [193]:
data = np.random.randn(2,3)
data

array([[ 0.38229727, -0.4069245 , -0.78335599],
       [-0.31588424,  0.40509468,  1.0814645 ]])

In [198]:
np.mean(data)

0.06044862121491895

In [218]:
#np.random.seed(42) Podemos definir una seed para que siempre nos de el mismo
data2 = np.random.randn(100,100)
np.mean(data2)

0.010806300296435794

# Comparacion entre rendimiento usando Numpy y usando Listas

In [221]:
%time for i in range(1000): np.arange(1000000)*2

CPU times: total: 3.42 s
Wall time: 3.61 s


In [223]:
%time for i in range(1000): list(range(1000000))*2

CPU times: total: 51 s
Wall time: 52.3 s


# Anadiendo elementos a arreglos de Numpy

In [228]:
a = np.array([1,2,3])
b = np.append(a, [4,5,6])

In [230]:
b

array([1, 2, 3, 4, 5, 6])

In [232]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [236]:
b = np.append([[9,9]], a, axis = 0)
b

array([[9, 9],
       [1, 2],
       [3, 4]])

In [244]:
c = np.append([[9,9]], a, axis = 1)
c

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1 and the array at index 1 has size 2

# Delete elements

In [247]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [249]:
np.delete(a,0)

array([2, 3, 4, 5, 6])

In [ ]:
np.delate