### Trabajando con matrices

#### Importamos librerias

In [2]:
import numpy as np
import cv2 as cv

In [36]:
A = np.array([[1,1,1], [1,1,1], [1,1,1]]) #definimos matriz

In [14]:
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [38]:
B = np.array([[1,2,3,], [4,5,6], [7,8,9]]) 
B_T = np.transpose(B)
print(B)
#print(B_T)

print("Normal")
print(A@B)

print("Matmul")
print(np.matmul(A,B)) #Necesario para multiplicar una matriz cuando es transpuesta

print("\n")


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normal
[[12 15 18]
 [12 15 18]
 [12 15 18]]
Matmul
[[12 15 18]
 [12 15 18]
 [12 15 18]]




In [12]:
I = np.ones((250,250),dtype= np.uint8) * 100 # multiplicacion por escalar
print(I)

[[100 100 100 ... 100 100 100]
 [100 100 100 ... 100 100 100]
 [100 100 100 ... 100 100 100]
 ...
 [100 100 100 ... 100 100 100]
 [100 100 100 ... 100 100 100]
 [100 100 100 ... 100 100 100]]


In [13]:
cv.imshow("Mi primer imagen", I)
cv.waitKey(0)

-1

In [11]:
Imagencita = cv.imread("example1.jpeg",0) *2

cv.imshow("Mi primer imagen", Imagencita)
cv.waitKey(0)

-1